#!/usr/bin/env node

// node ~/scripts/sshkeys ~/.ssh/id_rsa
'use strict';
const exec = require('child_process').exec;

var mode;
var sshKeyFilePath;

process.argv.forEach((arg, idx) => {
  if (idx === 0 || idx === 1) {
    // do nothing
    return;
  } else {
    // handle mode
    if (idx === 2) {
      sshKeyFilePath = arg;
    }  
    else {
      console.log('Only mode is required. ' +
                  'Please run again with two arguments: ' +
                  'mode and ssh key file path');
      process.exit(1)
    }
  }

});


let initialCommand = 'exit';
let secondCommand = 'eval \"\$(ssh-agent -s)\"; ' +
                    'ssh-add ' + sshKeyFilePath;

return new Promise((resolve, reject) => {
  
  const child1 = exec(initialCommand, (err, stdout, stderr) => {
    if (err) {
      reject(err)

    }
  });

  child1.on('exit', (code) => {});
  resolve()
}).then(() => {
  return new Promise((resolve, reject) => {
    const child2 = exec(secondCommand, (err, stdout, stderr) => {
      if (err) {
        reject(err)
      }
    });

    child2.on('exit', (code) => {});
    resolve()
  })
}).then(() => {
  
});